server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: resource-server
  
  # OAuth2 Resource Server Configuration
  security:
    oauth2:
      resourceserver:
        # JWT Token Validation using Authorization Server's JWK endpoint
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
          issuer-uri: http://localhost:9000
        # Alternative: Token Introspection (uncomment if you prefer introspection over JWT)
        # opaquetoken:
        #   introspection-uri: http://localhost:9000/oauth2/introspect
        #   client-id: api-client
        #   client-secret: api-secret

# Authorization Server Configuration
authorization-server:
  base-url: http://localhost:9000
  endpoints:
    token-validation: ${authorization-server.base-url}/api/oauth2/token/validate
    token-introspection: ${authorization-server.base-url}/api/oauth2/introspect
    jwks: ${authorization-server.base-url}/oauth2/jwks
    userinfo: ${authorization-server.base-url}/userinfo

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.sripiranavan.resource_server: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
